(() => {
'use strict';
const WA='https://wa.me/573023571724?text=Hola%20Juan%2C%20vi%20MEDACCER%20y%20quiero%20una%20demostraci%C3%B3n%20para%20mi%20consultorio.%20%C2%BFCu%C3%A1ndo%20podemos%20hablar%3F';
document.querySelectorAll('[data-demo-link]').forEach(a=>a.href=WA);
const header=document.querySelector('[data-header]');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>8),{passive:true});
const menuBtn=document.querySelector('.menu-button'),menu=document.querySelector('#mobile-menu');menuBtn?.addEventListener('click',()=>{const open=menuBtn.getAttribute('aria-expanded')==='true';menuBtn.setAttribute('aria-expanded',String(!open));menu.hidden=open});menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.hidden=true;menuBtn.setAttribute('aria-expanded','false')}));
const SPEC=[
{id:'general',label:'Medicina general',context:'Asistente del consultorio',pain:['10 h','por semana respondiendo mensajes que Ada podría atender'],scripts:{agendar:[['patient','Hola, ¿tienen cita con medicina general esta semana? 🙏'],['ada','¡Hola! 😊 Claro que sí. El Dr. Ramírez tiene:\n📅 Jueves 3:30 p. m.\n📅 Viernes 9:00 a. m.\n¿Cuál le queda mejor?'],['patient','El jueves, porfa'],['ada','¡Listo! ✅ Cita el jueves 3:30 p. m.\nLe escribo un día antes para recordarle. Que esté muy bien 💙']],duda:[['patient','es que no sé si lo mío es para general o especialista 😕'],['ada','Tranquilo/a, para eso estamos 🙌 Cuénteme qué siente y desde cuándo, y el Dr. Ramírez lo orienta en la consulta.\n¿Le agendo una valoración? Son $80.000.'],['patient','vale, agéndame'],['ada','¡Hecho! 📅 Mañana 10:00 a. m. Cualquier cosa, aquí estoy 💙']]}},
{id:'odontologia',label:'Odontología',context:'Asistente del consultorio dental',pain:['$10.8M','COP al mes que pierde un consultorio dental promedio por inasistencias'],scripts:{agendar:[['patient','¿Cuánto cuesta el diseño de sonrisa?'],['ada','¡Hola! 😁 Incluye valoración + diseño digital + carillas, desde $2.500.000.\n¿Le agendo una valoración?\n📅 Jueves 3:00 p. m.\n📅 Viernes 10:00 a. m.'],['patient','El jueves está bien'],['ada','✅ Cita el jueves 3:00 p. m.\n🦷 Valoración diseño de sonrisa.\nLe recuerdo 24 h antes 💙']],duda:[['ada','Hola María 👋 Hace 15 días le pasamos el presupuesto del diseño de sonrisa ($6.800.000). ¿Pudo revisarlo?\n💡 Tenemos financiación a 12 meses sin interés.'],['patient','justo lo estaba pensando, ¿cómo es la financiación?'],['ada','¡Perfecto! 🙌\n📊 12 cuotas: $566.000/mes (sin interés)\n📊 18 cuotas: $389.000/mes\n¿Le agendo para arrancar?']]}},
{id:'dermatologia',label:'Dermatología',context:'Asistente de la Dra. Morales',pain:['4 h','por semana que pierde un dermatólogo en consultas gratis por WhatsApp'],scripts:{agendar:[['patient','Tengo un lunar que cambió de color, quiero valoración'],['ada','Hola, soy Ada, asistente de la Dra. Morales 🌿\nPara adelantar, ¿me envía 2 fotos del lunar? Una de cerca y otra con algo de escala al lado. Van directo a su ficha.'],['patient','(📷 foto adjunta)'],['ada','📂 Recibido y guardado en su ficha.\nPara evaluarlo bien necesitamos dermatoscopia en consulta:\n📅 Mié 24 — 9:30 a. m.\n💰 $180.000']],duda:[['patient','granos en la espalda hace meses, ya probé de todo 😩'],['ada','Uf, el acné de espalda es frustrante, pero la Dra. lo trata muy bien 💪\n¿Hace cuánto salieron y usa algún tratamiento hormonal?'],['patient','6 meses, tomo anticonceptivos'],['ada','Gracias 🙌 Le agendo valoración con protocolo anti-acné ($180.000):\n📅 Vie 26 — 10:30 a. m.']]}},
{id:'psicologia',label:'Psicología',context:'Asistente de la Psi. Gómez',pain:['40%','de pacientes cancela por vergüenza o ansiedad antes de la sesión'],scripts:{agendar:[['patient','Quiero empezar terapia, nunca he ido antes'],['ada','Hola, soy Ada, asistente de la Psi. Gómez 💙\nMe alegra que dé este paso, es muy valiente. La primera sesión es de 60 min, sin juicios y a su ritmo.\n💰 $130.000 · 🔒 Confidencial'],['patient','gracias, prefiero en la tarde'],['ada','📅 Tardes esta semana:\n• Mar 23 — 4:00 p. m.\n• Jue 25 — 6:00 p. m.\n🔒 El recordatorio llega solo como "Cita con la Dra. Gómez".']],duda:[['ada','Hola María, ¿cómo se ha sentido esta semana? No hace falta que entre en detalles, solo saber cómo está 💙'],['patient','mejor que la semana pasada, gracias'],['ada','Me alegra mucho 😊 Le recuerdo su sesión del jueves 3:00 p. m. ¿La confirmo?'],['patient','sí, ahí estaré'],['ada','Perfecto, aquí la esperamos 🌿']]}},
{id:'nutricion',label:'Nutrición',context:'Asistente de la nutricionista Laura',pain:['70%','de pacientes abandona el plan en las primeras 2 semanas sin seguimiento'],scripts:{agendar:[['patient','Quiero un plan para bajar 8 kilos'],['ada','¡Hola! Soy Ada, asistente de la nutricionista Laura 🌱\nSu primera consulta incluye valoración, análisis de hábitos y plan de 30 días con recetas.\n💰 $150.000 (incluye control a los 15 días)'],['patient','listo, ¿qué me toca?'],['ada','📅 Jue 25 · 2:00 p. m.\n📋 Traiga exámenes recientes (si tiene) y qué come en un día normal 😊']],duda:[['ada','¡Hola Carlos! ¿Cómo le fue con la alimentación esta semana?\n1️⃣ Seguí el plan 💪\n2️⃣ Más o menos 😅\n3️⃣ No pude 😔'],['patient','2'],['ada','¡Lo importante es la constancia, no la perfección! 🌟 Su control es el martes. ¿Alguna duda del plan?']]}},
{id:'fisioterapia',label:'Fisioterapia',context:'Asistente del fisioterapeuta',pain:['60%','de pacientes abandona el tratamiento antes de terminar las sesiones'],scripts:{agendar:[['patient','El médico me mandó 10 sesiones por dolor lumbar'],['ada','¡Hola! 💪 Perfecto, lo acompañamos en todo el proceso. Cada sesión dura 45 min.\n¿Le armo el plan de las 10 sesiones fijas, mismo día y hora?'],['patient','sí, martes y jueves en la tarde'],['ada','✅ Listo, mar y jue 4:00 p. m. por 5 semanas.\nLe mando ejercicios para casa y le recuerdo cada sesión 🙌']],duda:[['ada','Hola 👋 ¿Hizo los ejercicios de casa hoy?\n✅ Hechos\n⚠️ A medias\n❌ No pude'],['patient','a medias, me dolió un poco'],['ada','Gracias por contarme 🙏 Le aviso al fisio para ajustar la intensidad. Vamos muy bien, ¡ya lleva 6 de 10! 📈']]}},
{id:'pediatria',label:'Pediatría',context:'Asistente del pediatra',pain:['11 p. m.','hora típica en que los padres preguntan por síntomas de sus hijos'],scripts:{agendar:[['patient','Mi bebé necesita el control de los 6 meses'],['ada','¡Hola! 👶 Con gusto. El control de niño sano incluye peso, talla y revisión del desarrollo.\n📅 Jue 25 — 9:00 a. m.\n💰 $180.000. ¿Se lo agendo?'],['patient','sí, ¿y toca vacuna?'],['ada','¡Buen dato! 💉 A los 6 meses toca refuerzo. Lo dejo anotado para el mismo día ✅']],duda:[['patient','son las 11 p. m. y mi hija tiene 38.5 de fiebre 😟'],['ada','Tranquila, la acompaño 💙 A 38.5 °C: líquidos y ropa ligera. Si pasa de 39 °C, no baja en 2 h o la ve decaída, vaya a urgencias.\n¿Le agendo control mañana temprano con el Dr.?'],['patient','sí, por favor'],['ada','📅 Mañana 8:00 a. m. Cualquier cambio esta noche, escríbame 🙏']]}},
{id:'estetica',label:'Medicina estética',context:'Asistente del consultorio estético',pain:['78%','de los reclamos en estética vienen de falta de seguimiento post-procedimiento'],scripts:{agendar:[['patient','Info sobre toxina botulínica porfa'],['ada','¡Hola! ✨ La aplicación incluye valoración facial y control a los 15 días.\n💰 Desde $650.000 (según zonas).\n¿Le agendo valoración? 📅 Lun 22 — 4:00 p. m.'],['patient','sí, pero ¿duele?'],['ada','Muy poco 😊 Usamos frío y microaguja; la mayoría lo siente como un piquetico. La Dra. le explica todo en la valoración ✅']],duda:[['ada','Hola 👋 ¿Cómo se ha sentido tras la aplicación de hace 3 días? ¿Algún enrojecimiento o molestia?'],['patient','todo bien, solo un moretoncito'],['ada','¡Es totalmente normal! 💛 Baja en unos días. Le recuerdo su control de retoque a los 15 días. ¡Se va a ver espectacular! ✨']]}}
];
const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const body=document.querySelector('[data-conversation]'),typing=document.querySelector('[data-typing]');let current=SPEC[0],scenario='agendar',timers=[];function clearTimers(){timers.forEach(clearTimeout);timers=[]}
function playCurrent(){if(!body)return;clearTimers();body.innerHTML='';typing.hidden=true;const msgs=current.scripts[scenario]||[];let t=250;msgs.forEach(m=>{const isAda=m[0]==='ada';if(isAda){timers.push(setTimeout(()=>{typing.hidden=false;body.scrollTop=body.scrollHeight},t));t+=650}timers.push(setTimeout(()=>{if(isAda)typing.hidden=true;const p=document.createElement('p');p.className='message '+m[0];p.innerHTML=esc(m[1]).replace(/\n/g,'<br>');body.appendChild(p);body.scrollTop=body.scrollHeight},t));t+=Math.min(1000,520+m[1].length*11)});timers.push(setTimeout(()=>{typing.hidden=true},t))}
const titleEl=document.querySelector('[data-convo-title]');function updateTitle(){if(titleEl)titleEl.textContent=`${current.label} · ${scenario==='agendar'?'Agendar cita':'Resolver una duda'}`}
function selectSpec(s){current=s;document.querySelectorAll('.specialty-chip').forEach(c=>c.setAttribute('aria-selected',String(c.dataset.spec===s.id)));const ctx=document.querySelector('[data-ada-context]');if(ctx)ctx.textContent=s.context;const pv=document.querySelector('[data-pain-value]'),pl=document.querySelector('[data-pain-label]');if(pv)pv.textContent=s.pain[0];if(pl)pl.textContent=s.pain[1];updateTitle();playCurrent()}
const chips=document.querySelector('[data-specialty-chips]');SPEC.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('role','tab');b.className='specialty-chip';b.dataset.spec=s.id;b.textContent=s.label;b.setAttribute('aria-selected',String(i===0));b.addEventListener('click',()=>selectSpec(s));chips?.append(b)});
document.querySelectorAll('[data-scenario]').forEach(btn=>btn.addEventListener('click',()=>{scenario=btn.dataset.scenario;document.querySelectorAll('[data-scenario]').forEach(b=>b.setAttribute('aria-selected',String(b===btn)));updateTitle();playCurrent()}));document.querySelector('[data-replay]')?.addEventListener('click',playCurrent);updateTitle();playCurrent();
document.querySelectorAll('[data-billing]').forEach(btn=>btn.addEventListener('click',()=>{const annual=btn.dataset.billing==='annual';document.querySelectorAll('[data-billing]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));document.querySelectorAll('[data-price]').forEach(p=>{const base=Number(p.dataset.price),value=annual?Math.round(base*.85/1000)*1000:base;p.textContent=new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value)})}));
document.querySelectorAll('.socials a[href="#"]').forEach(a=>a.addEventListener('click',e=>e.preventDefault()));
const cop=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);const roiInputs=document.querySelectorAll('[data-roi]');function updateRoi(){const v={};roiInputs.forEach(i=>v[i.dataset.roi]=Number(i.value));document.querySelector('[data-roi-out="misses"]').textContent=v.misses;document.querySelector('[data-roi-out="value"]').textContent=cop(v.value);document.querySelector('[data-roi-out="hours"]').textContent=v.hours+' h';const recovered=Math.round(v.misses*4.33*v.value*.45);const time=Math.round(v.hours*4.33*.6);const rEl=document.querySelector('[data-roi-recovered]'),tEl=document.querySelector('[data-roi-time]');if(rEl)rEl.textContent=cop(recovered);if(tEl)tEl.textContent=time+' h'}roiInputs.forEach(i=>i.addEventListener('input',updateRoi));if(roiInputs.length)updateRoi();
const videoSlot=document.querySelector('[data-video-src]');videoSlot?.querySelector('.video-play')?.addEventListener('click',()=>{const src=videoSlot.dataset.videoSrc;if(!src)return;const f=document.createElement('iframe');f.src=src;f.title='Video de demostración de MEDACCER';f.allow='accelerated-thumbnail; autoplay; encrypted-media; fullscreen';f.allowFullscreen=true;f.style.cssText='position:absolute;inset:0;width:100%;height:100%;border:0;z-index:3';videoSlot.appendChild(f)});
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduce&&'IntersectionObserver'in window){const revealObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>revealObs.observe(e));const countObs=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const n=Number(e.target.dataset.count),start=performance.now();function tick(t){const pct=Math.min((t-start)/900,1);e.target.textContent=Math.round(n*pct)+(n===40?'%':'+');if(pct<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);countObs.unobserve(e.target)}),{threshold:.7});document.querySelectorAll('[data-count]').forEach(e=>countObs.observe(e))}else{document.querySelectorAll('.reveal').forEach(e=>e.classList.add('visible'));document.querySelectorAll('[data-count]').forEach(e=>e.textContent=e.dataset.count+(e.dataset.count==='40'?'%':'+'))}
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimers();else playCurrent()});
})();
