(() => {
'use strict';
const WA='https://wa.me/573023571724?text=Hola%20Juan%2C%20vi%20MEDACCER%20y%20quiero%20una%20demostraci%C3%B3n%20para%20mi%20consultorio.%20%C2%BFCu%C3%A1ndo%20podemos%20hablar%3F';
document.querySelectorAll('[data-demo-link]').forEach(a=>a.href=WA);
const header=document.querySelector('[data-header]');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>8),{passive:true});
const menuBtn=document.querySelector('.menu-button'),menu=document.querySelector('#mobile-menu');menuBtn?.addEventListener('click',()=>{const open=menuBtn.getAttribute('aria-expanded')==='true';menuBtn.setAttribute('aria-expanded',String(!open));menu.hidden=open});menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.hidden=true;menuBtn.setAttribute('aria-expanded','false')}));
const conversations={agendar:[['patient','Hola, ¿hay cita de valoración esta semana?'],['ada','Claro. La doctora tiene disponibilidad el jueves a las 3:30 p. m. y el viernes a las 10:00 a. m.'],['patient','El jueves está perfecto.'],['ada','Listo. Reservé el jueves a las 3:30 p. m. Le enviaré la confirmación y el recordatorio por este medio.']],reprogramar:[['patient','Ada, no alcanzo a llegar mañana. ¿Puedo mover mi cita?'],['ada','Por supuesto. Puedo ofrecerle el viernes a las 11:00 a. m. o el lunes a las 2:00 p. m.'],['patient','El lunes, por favor.'],['ada','Hecho. Su cita quedó para el lunes a las 2:00 p. m. y el espacio de mañana vuelve a estar disponible.']],seguimiento:[['ada','Hola, María. ¿Cómo se ha sentido después de su consulta?'],['patient','Mucho mejor, gracias. Solo tengo una duda sobre las indicaciones.'],['ada','Puedo compartirle las instrucciones registradas. Si su duda requiere una decisión clínica, la enviaré al consultorio para revisión.'],['patient','Perfecto, muchas gracias.']]};
const body=document.querySelector('[data-conversation]'),typing=document.querySelector('[data-typing]');let scenario='agendar',timers=[];function clearTimers(){timers.forEach(clearTimeout);timers=[]}function play(){if(!body)return;clearTimers();body.innerHTML='';typing.hidden=false;conversations[scenario].forEach((item,i)=>timers.push(setTimeout(()=>{const p=document.createElement('p');p.className=`message ${item[0]}`;p.textContent=item[1];body.appendChild(p);body.scrollTop=body.scrollHeight;if(i===conversations[scenario].length-1)typing.hidden=true},350+i*850)))}
document.querySelectorAll('[data-scenario]').forEach(btn=>btn.addEventListener('click',()=>{scenario=btn.dataset.scenario;document.querySelectorAll('[data-scenario]').forEach(b=>b.setAttribute('aria-selected',String(b===btn)));play()}));document.querySelector('[data-replay]')?.addEventListener('click',play);play();
const specialties=[['Odontología','Citas y controles'],['Dermatología','Seguimientos visuales'],['Psicología','Agenda confidencial'],['Nutrición','Planes y controles'],['Medicina estética','Valoraciones'],['Fisioterapia','Sesiones recurrentes'],['Pediatría','Controles y vacunas'],['Ginecología','Seguimiento continuo'],['Medicina general','Atención integral']];function specialtyButton([name,desc],i){const b=document.createElement('button');b.type='button';b.className='specialty-button';b.innerHTML=`<span class="specialty-icon">${String(i+1).padStart(2,'0')}</span><span><strong>${name}</strong><small>${desc}</small></span>`;b.addEventListener('click',()=>{document.querySelectorAll('.specialty-button').forEach(x=>x.classList.toggle('active',x.querySelector('strong')?.textContent===name));scenario=name==='Psicología'?'seguimiento':name==='Fisioterapia'?'reprogramar':'agendar';document.querySelectorAll('[data-scenario]').forEach(x=>x.setAttribute('aria-selected',String(x.dataset.scenario===scenario)));dialog?.close();document.querySelector('#demo')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});play()});return b}const grid=document.querySelector('[data-specialty-grid]'),all=document.querySelector('[data-all-specialties]');specialties.slice(0,6).forEach((s,i)=>grid?.append(specialtyButton(s,i)));specialties.forEach((s,i)=>all?.append(specialtyButton(s,i)));
const dialog=document.querySelector('[data-specialty-dialog]'),openBtn=document.querySelector('[data-open-specialties]'),closeBtn=document.querySelector('[data-close-specialties]');openBtn?.addEventListener('click',()=>dialog.showModal());closeBtn?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.querySelectorAll('[data-billing]').forEach(btn=>btn.addEventListener('click',()=>{const annual=btn.dataset.billing==='annual';document.querySelectorAll('[data-billing]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));document.querySelectorAll('[data-price]').forEach(p=>{const base=Number(p.dataset.price),value=annual?Math.round(base*.85/1000)*1000:base;p.textContent=new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value)})}));
document.querySelectorAll('.socials a[href="#"]').forEach(a=>a.addEventListener('click',e=>e.preventDefault()));
const cop=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);const roiInputs=document.querySelectorAll('[data-roi]');function updateRoi(){const v={};roiInputs.forEach(i=>v[i.dataset.roi]=Number(i.value));document.querySelector('[data-roi-out="misses"]').textContent=v.misses;document.querySelector('[data-roi-out="value"]').textContent=cop(v.value);document.querySelector('[data-roi-out="hours"]').textContent=v.hours+' h';const recovered=Math.round(v.misses*4.33*v.value*.45);const time=Math.round(v.hours*4.33*.6);const rEl=document.querySelector('[data-roi-recovered]'),tEl=document.querySelector('[data-roi-time]');if(rEl)rEl.textContent=cop(recovered);if(tEl)tEl.textContent=time+' h'}roiInputs.forEach(i=>i.addEventListener('input',updateRoi));if(roiInputs.length)updateRoi();
const videoSlot=document.querySelector('[data-video-src]');videoSlot?.querySelector('.video-play')?.addEventListener('click',()=>{const src=videoSlot.dataset.videoSrc;if(!src)return;const f=document.createElement('iframe');f.src=src;f.title='Video de demostración de MEDACCER';f.allow='accelerated-thumbnail; autoplay; encrypted-media; fullscreen';f.allowFullscreen=true;f.style.cssText='position:absolute;inset:0;width:100%;height:100%;border:0;z-index:3';videoSlot.appendChild(f)});
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduce&&'IntersectionObserver'in window){const revealObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>revealObs.observe(e));const countObs=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const n=Number(e.target.dataset.count),start=performance.now();function tick(t){const pct=Math.min((t-start)/900,1);e.target.textContent=Math.round(n*pct)+(n===40?'%':'+');if(pct<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);countObs.unobserve(e.target)}),{threshold:.7});document.querySelectorAll('[data-count]').forEach(e=>countObs.observe(e))}else{document.querySelectorAll('.reveal').forEach(e=>e.classList.add('visible'));document.querySelectorAll('[data-count]').forEach(e=>e.textContent=e.dataset.count+(e.dataset.count==='40'?'%':'+'))}
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimers();else play()});
})();
